name: scial_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.2.1

  supabase_flutter: ^2.8.1

  firebase_core: ^3.8.1

  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.6.1

  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  go_router_builder: ^2.7.1

flutter:
  uses-material-design: true

  assets:
    - .env